drop table if exists signals;
create table signals(
    id bigint generated by default as identity,
    signal_id bigint,
    methods varchar(255),
    description varchar(255),
    primary key (id)
);
